// This file is auto-generated by the FlutterFire CLI.
// Replace the values below with your actual Firebase project configuration.
import 'package:firebase_core/firebase_core.dart';

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return const FirebaseOptions(
      apiKey: 'AIzaSyCShDWLjfXKtlHjo67li-f3pvfD2jYUvoU',
      appId: '1:1047142319245:android:5e0a1a03eb60ed9fc50ec4',
      messagingSenderId: '1047142319245',
      projectId: 'shamseih-chat',
      authDomain: 'shamseih-chat.firebaseapp.com',
      storageBucket: 'shamseih-chat.appspot.com',
      measurementId: 'G-498262267',
    );
  }
}
